# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
gem 'pg'
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 30051997
  host: localhost  
  port: 5432

development:
  <<: *default
  database: example_rails_dev

test:
  <<: *default
  database: example_rails_test

production:
  <<: *default
  database: example_rails_production

